name: Docker-Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --progress=plain -t blank_webapp .
